In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
import re

In [2]:
plots = []
prices = []
Construction = []
totalarea = []
area = []
location = []
cityname=[]
builder = []
status = []

for x in range(3,25):
    url = "https://www.makaan.com/listings?beds=1,2,3,3plus&propertyType=apartment,builder-floor,villa,residential-plot,independent-house,studio-apartment&budget=0,&furnished=unfurnished,semifurnished,furnished&listingType=buy&pageType=CITY_URLS&cityName=Hyderabad&cityId=12&templateId=MAKAAN_CITY_LISTING_BUY&page={}".format(x)
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    for x in soup.find_all('div',class_ = 'title-line'):
        plots.append(x.text)
    
    for x in soup.find_all("td",class_="price"):
        prices.append(x.text)
    
    for x in soup.find_all("td",class_="val"):
        Construction.append(x.text)
    
    for x in soup.find_all("td",class_="size"):
        totalarea.append(x.text)
    
    for x in soup.find_all("td",class_="lbl rate"):
        area.append(x.text)
    
    
    for x in soup.find_all('span',class_="cityName"):
        cityname.append(x.text)
    
    
    for x in soup.find_all("span",itemprop="addressLocality"):
       location.append(x.text)
    
    
    
    for x in soup.find_all("div",class_="seller-info"):
        builder.append(x.text)
        m = []
        for val in builder:
            bui = re.compile("BUILDER0",re.I)    
            m.append(bui.sub("",str(val)))
    
for x in range(3,25):
    url = "https://www.makaan.com/bangalore-residential-property/buy-property-in-bangalore-city?beds=1,2,3,3plus&propertyType=apartment,builder-floor,villa,residential-plot,independent-house,studio-apartment&budget=0,&furnished=unfurnished,semifurnished,furnished&page={}&_=1673964857131".format(x)
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    for x in soup.find_all('div',class_ = 'title-line'):
        plots.append(x.text)
    
    for x in soup.find_all("td",class_="price"):
        prices.append(x.text)
    
    for x in soup.find_all("td",class_="val"):
        Construction.append(x.text)
    
    for x in soup.find_all("td",class_="size"):
        totalarea.append(x.text)
    
    for x in soup.find_all("td",class_="lbl rate"):
        area.append(x.text)
    
    for x in soup.find_all('span',class_="cityName"):
        cityname.append(x.text)
    
    
    for x in soup.find_all("span",itemprop="addressLocality"):
       location.append(x.text)
    
    for x in soup.find_all("div",class_="seller-info"):
        builder.append(x.text)
        m = []
        for val in builder:
            bui = re.compile("BUILDER0",re.I)    
            m.append(bui.sub("",str(val)))

In [3]:
df3 = pd.DataFrame({"Plot_Specification":plots,"Prices":prices,"Construction Status":Construction,"Total Area":totalarea,"Price per Sq ft":area,"Location":location,"city":cityname,"Builder":m})

In [4]:
df3

,Plot_Specification,Prices,Construction Status,Total Area,Price per Sq ft,Location,city,Builder
0,3 BHK Apartment in Vajra The Royal Park,64.47 L,Under Construction,1535,"4,200 / sq ft",Bowrampet,Hyderabad,Vajra Builders And Developers
1,3 BHK Apartment in Vasavi Signature,1.82 Cr,Ready to move,2285,"8,000 / sq ft",Kukatpally,Hyderabad,Vasavi Group
2,3 BHK Apartment in Riddhi Pramukh Elegance,87.58 L,Under Construction,1510,"5,800 / sq ft",Jeedimetla,Hyderabad,Riddhi Group
3,4 BHK Apartment in Theme Imperial,1.8 Cr,Under Construction,2655,"6,800 / sq ft",Attapur,Hyderabad,Theme Ambience Infrastructures
4,3 BHK Apartment in Signature Altius,1.21 Cr,Under Construction,2425,"4,999 / sq ft",Kollur,Hyderabad,Signature Avenues
...,...,...,...,...,...,...,...,...
875,3 BHK Apartment in Godrej Air Nxt,1.37 Cr,Under Construction,1817,"7,539 / sq ft",ITPL,Bangalore,Godrej Properties Ltd
876,3 BHK Apartment in Godrej Air Nxt,1.36 Cr,Under Construction,1761,"7,722 / sq ft",ITPL,Bangalore,Godrej Properties Ltd
877,1 BHK Apartment in Godrej Air Nxt,61 L,Under Construction,760,"8,026 / sq ft",ITPL,Bangalore,Godrej Properties Ltd
878,6 BHK Independent House,2 Cr,Ready to move,2250,"8,888 / sq ft",Banashankari,Bangalore,sellerVERIFIED OWNER
879,3 BHK Apartment,65 L,Ready to move,1500,"4,333 / sq ft",Subramanyapura,Bangalore,sellerVERIFIED OWNER

In [5]:
df3.Plot_Specification.value_counts()

2 BHK Apartment                                             87
2 BHK Apartment in Saroj Blue bells                         46
3 BHK Apartment                                             40
3 BHK Apartment in Vasavi Signature                         27
3 BHK Apartment in Vasavi Skyla                             22
                                                            ..
3 BHK Apartment in Sattva Park Cubix                         1
2 BHK Apartment in Reputed Builder VMR Geminis Signature     1
2 BHK Apartment in Esteem Kings Court                        1
2 BHK Apartment in Elegant 555                               1
1 BHK Apartment in Godrej Air Nxt                            1
Name: Plot_Specification, Length: 245, dtype: int64

# extracting bhk

In [6]:
df3['BHK']=df3.Plot_Specification.apply(lambda x: x.split(' ')[0])

In [7]:
df3

,Plot_Specification,Prices,Construction Status,Total Area,Price per Sq ft,Location,city,Builder,BHK
0,3 BHK Apartment in Vajra The Royal Park,64.47 L,Under Construction,1535,"4,200 / sq ft",Bowrampet,Hyderabad,Vajra Builders And Developers,3
1,3 BHK Apartment in Vasavi Signature,1.82 Cr,Ready to move,2285,"8,000 / sq ft",Kukatpally,Hyderabad,Vasavi Group,3
2,3 BHK Apartment in Riddhi Pramukh Elegance,87.58 L,Under Construction,1510,"5,800 / sq ft",Jeedimetla,Hyderabad,Riddhi Group,3
3,4 BHK Apartment in Theme Imperial,1.8 Cr,Under Construction,2655,"6,800 / sq ft",Attapur,Hyderabad,Theme Ambience Infrastructures,4
4,3 BHK Apartment in Signature Altius,1.21 Cr,Under Construction,2425,"4,999 / sq ft",Kollur,Hyderabad,Signature Avenues,3
...,...,...,...,...,...,...,...,...,...
875,3 BHK Apartment in Godrej Air Nxt,1.37 Cr,Under Construction,1817,"7,539 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,3
876,3 BHK Apartment in Godrej Air Nxt,1.36 Cr,Under Construction,1761,"7,722 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,3
877,1 BHK Apartment in Godrej Air Nxt,61 L,Under Construction,760,"8,026 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,1
878,6 BHK Independent House,2 Cr,Ready to move,2250,"8,888 / sq ft",Banashankari,Bangalore,sellerVERIFIED OWNER,6
879,3 BHK Apartment,65 L,Ready to move,1500,"4,333 / sq ft",Subramanyapura,Bangalore,sellerVERIFIED OWNER,3

In [8]:
df3['BHK']

0      3
1      3
2      3
3      4
4      3
      ..
875    3
876    3
877    1
878    6
879    3
Name: BHK, Length: 880, dtype: object

# extracting plot specification

In [9]:
df3['Plot_Specification']=df3.Plot_Specification.apply(lambda x: x.split(' ')[2])

In [10]:
df3

,Plot_Specification,Prices,Construction Status,Total Area,Price per Sq ft,Location,city,Builder,BHK
0,Apartment,64.47 L,Under Construction,1535,"4,200 / sq ft",Bowrampet,Hyderabad,Vajra Builders And Developers,3
1,Apartment,1.82 Cr,Ready to move,2285,"8,000 / sq ft",Kukatpally,Hyderabad,Vasavi Group,3
2,Apartment,87.58 L,Under Construction,1510,"5,800 / sq ft",Jeedimetla,Hyderabad,Riddhi Group,3
3,Apartment,1.8 Cr,Under Construction,2655,"6,800 / sq ft",Attapur,Hyderabad,Theme Ambience Infrastructures,4
4,Apartment,1.21 Cr,Under Construction,2425,"4,999 / sq ft",Kollur,Hyderabad,Signature Avenues,3
...,...,...,...,...,...,...,...,...,...
875,Apartment,1.37 Cr,Under Construction,1817,"7,539 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,3
876,Apartment,1.36 Cr,Under Construction,1761,"7,722 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,3
877,Apartment,61 L,Under Construction,760,"8,026 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,1
878,Independent,2 Cr,Ready to move,2250,"8,888 / sq ft",Banashankari,Bangalore,sellerVERIFIED OWNER,6
879,Apartment,65 L,Ready to move,1500,"4,333 / sq ft",Subramanyapura,Bangalore,sellerVERIFIED OWNER,3

In [11]:
df3.Plot_Specification.value_counts()

Apartment      770
Independent     64
Villa           46
Name: Plot_Specification, dtype: int64

# converting prices into lakhs

In [12]:
rate=[]
for i in df3['Prices']:
    if i.split()[-1]=='Cr':
        rate.append(round(float(i.split()[0])*100,2))
    else:
        rate.append(float(i.split()[0]))

In [13]:
rate

[64.47,
 182.0,
 87.58,
 180.0,
 121.0,
 54.67,
 135.0,
 71.18,
 219.0,
 133.0,
 69.98,
 109.0,
 54.14,
 46.87,
 118.0,
 930.0,
 62.12,
 49.86,
 74.51,
 102.0,
 121.0,
 79.71,
 129.0,
 97.7,
 130.0,
 168.0,
 53.55,
 226.0,
 114.0,
 147.0,
 69.23,
 53.8,
 160.0,
 57.56,
 219.0,
 129.0,
 44.61,
 50.83,
 168.0,
 31.0,
 50.0,
 58.0,
 99.0,
 350.0,
 85.0,
 49.0,
 59.69,
 90.0,
 84.0,
 60.0,
 69.54,
 145.0,
 48.5,
 169.0,
 210.0,
 45.0,
 46.55,
 64.5,
 66.0,
 80.0,
 58.8,
 62.41,
 66.94,
 118.0,
 209.0,
 209.0,
 118.0,
 118.0,
 129.0,
 129.0,
 178.0,
 178.0,
 157.0,
 157.0,
 707.0,
 495.0,
 99.56,
 84.48,
 74.34,
 49.86,
 87.35,
 87.35,
 59.13,
 59.13,
 74.51,
 91.91,
 91.91,
 98.58,
 98.58,
 96.72,
 77.1,
 63.0,
 83.82,
 83.7,
 121.0,
 111.0,
 111.0,
 88.4,
 88.4,
 118.0,
 118.0,
 81.57,
 81.57,
 82.55,
 82.55,
 55.23,
 55.23,
 129.0,
 99.92,
 99.92,
 169.0,
 169.0,
 113.0,
 113.0,
 79.71,
 109.0,
 109.0,
 74.72,
 74.72,
 94.71,
 94.71,
 90.7,
 71.41,
 103.0,
 170.0,
 69.0,
 111.0,
 146.0,
 195.0,
 186.0,
 150.0,
 120.0,
 155.0,
 147.0,
 96.24,
 70.35,
 226.0,
 184.0,
 184.0,
 142.0,
 142.0,
 256.0,
 256.0,
 140.0,
 140.0,
 156.0,
 156.0,
 192.0,
 192.0,
 167.0,
 167.0,
 168.0,
 168.0,
 144.0,
 144.0,
 220.0,
 220.0,
 155.0,
 155.0,
 166.0,
 166.0,
 110.0,
 118.0,
 168.0,
 114.0,
 117.0,
 63.8,
 106.0,
 71.34,
 93.09,
 120.0,
 144.0,
 69.31,
 175.0,
 111.0,
 150.0,
 182.0,
 127.0,
 65.83,
 108.0,
 80.95,
 107.0,
 81.77,
 104.0,
 125.0,
 153.0,
 141.0,
 93.73,
 77.48,
 90.98,
 70.98,
 109.0,
 69.98,
 81.73,
 55.0,
 52.0,
 53.0,
 53.0,
 53.0,
 37.0,
 37.0,
 53.0,
 35.0,
 37.0,
 54.0,
 37.0,
 37.0,
 37.0,
 52.0,
 155.0,
 53.0,
 44.0,
 167.0,
 61.0,
 68.0,
 68.5,
 53.0,
 53.0,
 53.0,
 57.36,
 83.0,
 73.43,
 58.0,
 62.0,
 59.0,
 70.0,
 56.0,
 56.0,
 57.36,
 110.0,
 60.18,
 99.4,
 66.5,
 62.0,
 55.0,
 51.0,
 58.0,
 56.0,
 50.49,
 59.85,
 69.98,
 57.6,
 120.0,
 54.97,
 40.0,
 55.48,
 87.0,
 2150.0,
 60.0,
 130.0,
 95.0,
 60.0,
 180.0,
 31.0,
 155.0,
 1000.0,
 219.0,
 125.0,
 125.0,
 530.0,
 72.0,
 72.0,
 32.0,
 38.0,
 90.0,
 322.0,
 86.0,
 69.0,
 96.89,
 55.91,
 38.0,
 47.0,
 65.0,
 38.5,
 60.0,
 57.0,
 150.0,
 38.5,
 81.75,
 62.0,
 300.0,
 75.0,
 75.0,
 246.0,
 135.0,
 90.0,
 44.27,
 130.0,
 95.0,
 67.0,
 28.5,
 125.0,
 200.0,
 625.0,
 59.99,
 110.0,
 67.0,
 75.0,
 33.59,
 127.0,
 175.0,
 125.0,
 90.0,
 85.0,
 75.0,
 200.0,
 110.0,
 75.0,
 44.93,
 42.0,
 50.4,
 600.0,
 96.0,
 162.0,
 96.7,
 53.0,
 1498.0,
 49.5,
 101.0,
 63.0,
 92.0,
 190.0,
 78.0,
 135.0,
 90.0,
 230.0,
 37.0,
 95.0,
 58.0,
 55.0,
 66.0,
 73.1,
 36.0,
 55.7,
 101.0,
 68.0,
 40.0,
 31.0,
 48.0,
 92.0,
 55.0,
 406.0,
 406.0,
 163.0,
 163.0,
 326.0,
 326.0,
 406.0,
 406.0,
 163.0,
 163.0,
 326.0,
 326.0,
 191.0,
 191.0,
 267.0,
 267.0,
 203.0,
 203.0,
 141.0,
 141.0,
 151.0,
 151.0,
 54.0,
 56.0,
 93.0,
 139.0,
 68.0,
 95.0,
 62.0,
 175.0,
 65.4,
 108.0,
 91.84,
 41.46,
 54.23,
 36.73,
 62.28,
 45.48,
 62.08,
 58.0,
 68.0,
 64.0,
 250.0,
 42.5,
 250.0,
 84.0,
 69.0,
 150.0,
 87.0,
 45.0,
 96.9,
 100.0,
 80.0,
 98.0,
 41.0,
 42.0,
 37.0,
 250.0,
 320.0,
 368.0,
 319.0,
 203.0,
 250.0,
 318.0,
 252.0,
 373.0,
 201.0,
 371.0,
 226.0,
 225.0,
 202.0,
 403.0,
 220.0,
 267.0,
 452.0,
 198.0,
 404.0,
 269.0,
 265.0,
 640.0,
 196.0,
 392.0,
 285.0,
 214.0,
 286.0,
 189.0,
 212.0,
 213.0,
 534.0,
 396.0,
 427.0,
 186.0,
 323.0,
 424.0,
 573.0,
 431.0,
 327.0,
 570.0,
 350.0,
 97.99,
 83.87,
 78.77,
 133.0,
 34.01,
 41.99,
 62.32,
 40.34,
 77.83,
 65.57,
 85.02,
 36.09,
 90.6,
 144.0,
 120.0,
 65.0,
 39.5,
 69.66,
 75.58,
 97.77,
 91.7,
 62.72,
 49.52,
 122.0,
 70.0,
 80.45,
 157.0,
 89.0,
 83.21,
 44.46,
 102.0,
 38.96,
 58.98,
 68.44,
 39.49,
 55.61,
 97.63,
 103.0,
 28.95,
 83.08,
 137.0,
 270.0,
 76.0,
 39.5,
 41.4,
 56.0,
 65.0,
 82.8,
 18.5,
 50.0,
 120.0,
 77.2,
 130.0,
 130.0,
 59.0,
 170.0,
 150.0,
 60.0,
 125.0,
 50.0,
 87.58,
 71.38,
 91.78,
 88.26,
 108.0,
 85.01,
 94.69,
 91.7,
 91.26,
 91.26,
 114.0,
 114.0,
 62.72,
 45.66,
 45.66,
 46.12,
 62.71,
 46.12,
 62.71,
 61.25,
 61.25,
 52.0,
 52.0,
 66.35,
 66.35,
 48.2,
 48.2,
 67.23,
 67.23,
 52.41,
 52.41,
 30.99,
 30.99,
 30.94,
 30.94,
 67.65,
 67.65,
 49.52,
 65.16,
 65.16,
 55.17,
 55.17,
 47.56,
 47.56,
 75.81,
 75.81,
 54.08,
 54.08,
 56.04,
 56.04,
 57.34,
 57.34,
 66.47,
 66.47,
 47.34,
 47.34,
 122.0,
 126.0,
 126.0,
 250.0,
 250.0,
 70.0,
 77.0,
 77.0,
 87.0,
 87.0,
 76.0,
 76.0,
 85.1,
 85.1,
 89.0,
 89.0,
 80.45,
 77.38,
 77.38,
 76.13,
 82.91,
 76.13,
 76.75,
 82.91,
 83.52,
 76.75,
 79.53,
 83.52,
 79.53,
 87.52,
 79.22,
 87.52,
 86.29,
 79.22,
 86.29,
 81.99,
 81.99,
 77.99,
 77.99,
 89.97,
 89.97,
 74.88,
 78.61,
 74.88,
 74.62,
 78.61,
 74.62,
 82.29,
 82.29,
 74.25,
 74.25,
 73.94,
 73.94,
 78.0,
 78.0,
 93.66,
 93.66,
 77.38,
 77.38,
 85.37,
 85.37,
 200.0,
 89.0,
 83.21,
 84.0,
 84.0,
 83.34,
 83.34,
 83.14,
 83.14,
 82.21,
 82.21,
 84.54,
 84.54,
 80.75,
 80.75,
 84.07,
 84.07,
 94.7,
 74.26,
 74.19,
 74.13,
 73.93,
 73.87,
 43.3,
 81.03,
 53.3,
 42.91,
 92.64,
 59.42,
 59.75,
 44.66,
 95.99,
 102.0,
 134.0,
 95.99,
 134.0,
 38.96,
 45.44,
 45.44,
 47.51,
 47.51,
 35.54,
 35.54,
 45.47,
 45.47,
 58.98,
 42.98,
 42.98,
 57.98,
 57.98,
 68.72,
 68.56,
 67.33,
 70.95,
 71.23,
 67.61,
 77.35,
 88.2,
 88.2,
 66.22,
 63.16,
 66.78,
 45.01,
 66.37,
 59.4,
 50.17,
 50.62,
 59.62,
 46.12,
 64.35,
 60.07,
 49.5,
 55.61,
 69.81,
 82.0,
 76.95,
 58.3,
 30.96,
 28.53,
 30.21,
 41.13,
 41.22,
 27.99,
 40.77,
 41.4,
 33.51,
 41.34,
 35.82,
 43.71,
 36.03,
 35.94,
 39.27,
 38.7,
 38.64,
 38.94,
 39.0,
 61.83,
 57.6,
 38.58,
 41.82,
 37.98,
 38.1,
 65.0,
 235.0,
 39.9,
 50.0,
 70.0,
 85.0,
 325.0,
 96.0,
 77.0,
 44.5,
 66.0,
 225.0,
 80.0,
 78.0,
 60.0,
 50.0,
 70.0,
 70.0,
 175.0,
 11.99,
 69.0,
 60.0,
 71.0,
 56.34,
 50.0,
 139.0,
 139.0,
 33.55,
 130.0,
 130.0,
 52.0,
 67.0,
 99.0,
 60.0,
 39.0,
 54.5,
 40.0,
 69.55,
 65.0,
 380.0,
 39.0,
 310.0,
 85.0,
 63.8,
 63.8,
 75.4,
 75.4,
 63.8,
 63.8,
 75.4,
 75.4,
 90.0,
 81.96,
 81.96,
 81.96,
 81.96,
 59.0,
 59.0,
 69.73,
 69.73,
 59.0,
 59.0,
 69.73,
 69.73,
 77.32,
 77.32,
 77.32,
 77.32,
 40.0,
 53.71,
 77.0,
 67.0,
 99.0,
 65.0,
 110.0,
 50.0,
 205.0,
 79.0,
 65.0,
 75.0,
 87.5,
 48.0,
 109.0,
 87.0,
 98.0,
 76.0,
 45.0,
 48.5,
 58.0,
 77.0,
 44.0,
 52.0,
 60.0,
 96.0,
 79.0,
 50.0,
 75.0,
 77.0,
 75.0,
 150.0,
 20.0,
 225.0,
 120.0,
 98.0,
 44.99,
 115.0,
 46.0,
 220.0,
 59.0,
 90.0,
 185.0,
 120.0,
 73.0,
 179.0,
 205.0,
 75.5,
 44.75,
 63.0,
 110.0,
 78.0,
 326.0,
 36.0,
 100.0,
 85.0,
 90.0,
 200.0,
 99.0,
 97.0,
 225.0,
 45.0,
 510.0,
 190.0,
 190.0,
 125.0,
 88.99,
 48.0,
 89.06,
 83.14,
 70.16,
 87.88,
 70.05,
 55.0,
 60.0,
 425.0,
 450.0,
 62.0,
 129.0,
 51.0,
 220.0,
 88.0,
 106.0,
 275.0,
 110.0,
 50.0,
 94.0,
 118.0,
 137.0,
 136.0,
 61.0,
 200.0,
 65.0]

In [14]:
df3['price(in_lakhs)']=rate
df3.drop('Prices',axis=1,inplace=True)

In [15]:
df3

,Plot_Specification,Construction Status,Total Area,Price per Sq ft,Location,city,Builder,BHK,price(in_lakhs)
0,Apartment,Under Construction,1535,"4,200 / sq ft",Bowrampet,Hyderabad,Vajra Builders And Developers,3,64.47
1,Apartment,Ready to move,2285,"8,000 / sq ft",Kukatpally,Hyderabad,Vasavi Group,3,182.00
2,Apartment,Under Construction,1510,"5,800 / sq ft",Jeedimetla,Hyderabad,Riddhi Group,3,87.58
3,Apartment,Under Construction,2655,"6,800 / sq ft",Attapur,Hyderabad,Theme Ambience Infrastructures,4,180.00
4,Apartment,Under Construction,2425,"4,999 / sq ft",Kollur,Hyderabad,Signature Avenues,3,121.00
...,...,...,...,...,...,...,...,...,...
875,Apartment,Under Construction,1817,"7,539 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,3,137.00
876,Apartment,Under Construction,1761,"7,722 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,3,136.00
877,Apartment,Under Construction,760,"8,026 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,1,61.00
878,Independent,Ready to move,2250,"8,888 / sq ft",Banashankari,Bangalore,sellerVERIFIED OWNER,6,200.00
879,Apartment,Ready to move,1500,"4,333 / sq ft",Subramanyapura,Bangalore,sellerVERIFIED OWNER,3,65.00

# converting DataFrame intp csv file

In [16]:
df3.to_csv('RealestateProjectManoj.csv')

In [17]:
df = pd.read_csv('RealestateProjectManoj.csv')

In [18]:
df

,Unnamed: 0,Plot_Specification,Construction Status,Total Area,Price per Sq ft,Location,city,Builder,BHK,price(in_lakhs)
0,0,Apartment,Under Construction,1535,"4,200 / sq ft",Bowrampet,Hyderabad,Vajra Builders And Developers,3,64.47
1,1,Apartment,Ready to move,2285,"8,000 / sq ft",Kukatpally,Hyderabad,Vasavi Group,3,182.00
2,2,Apartment,Under Construction,1510,"5,800 / sq ft",Jeedimetla,Hyderabad,Riddhi Group,3,87.58
3,3,Apartment,Under Construction,2655,"6,800 / sq ft",Attapur,Hyderabad,Theme Ambience Infrastructures,4,180.00
4,4,Apartment,Under Construction,2425,"4,999 / sq ft",Kollur,Hyderabad,Signature Avenues,3,121.00
...,...,...,...,...,...,...,...,...,...,...
875,875,Apartment,Under Construction,1817,"7,539 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,3,137.00
876,876,Apartment,Under Construction,1761,"7,722 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,3,136.00
877,877,Apartment,Under Construction,760,"8,026 / sq ft",ITPL,Bangalore,Godrej Properties Ltd,1,61.00
878,878,Independent,Ready to move,2250,"8,888 / sq ft",Banashankari,Bangalore,sellerVERIFIED OWNER,6,200.00
879,879,Apartment,Ready to move,1500,"4,333 / sq ft",Subramanyapura,Bangalore,sellerVERIFIED OWNER,3,65.00